# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mccrw.com
email: bmccraw86@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3>Hello, world!</h3><h1>DevJournal</h1><h3>A New Developer's Blog!</h3>Hope you find something good!"



baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mccrw.com" # the base hostname & protocol for your site
twitter_username: bmccraw86
github_username:  bmccraw86

# Build settings
markdown: kramdown
